name: Build and Push Docker Image

on:
  push:
    branches: [ main ]

env:
  DOCKERHUB_USERNAME: melaku8080
  IMAGE_NAME: html-login-page

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t $DOCKERHUB_USERNAME/$IMAGE_NAME:latest .

      - name: Push to Docker Hub
        run: |
          docker push $DOCKERHUB_USERNAME/$IMAGE_NAME:latest
