name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'html-login-page/**'
      - 'Dockerfile'
  
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Navigate to project folder
        run: cd html-login-page

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: melaku8080
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./html-login-page
          push: true
          tags: |
            melaku8080/login_repo:latest
            melaku8080/login_repo:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
